server:
  port: 8090

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/loan
    username: postgres
    password: 1234
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
  application:
    name: LOAN-MANAGEMENT